import { PublicKey, SystemProgram, SYSVAR_RENT_PUBKEY, Connection } from "@solana/web3.js";
import { BN } from "@coral-xyz/anchor";
import { getProgram } from "../config/program";
import { phantomWalletAdapter } from "../wallet/phantomWalletAdapter";
import { createProvider } from "../wallet/walletSession";
import { findUserAttendancePda } from "../pda/userAttendancePda";
import { findBadgeCollectionPda } from "../pda/badgeCollectionPda";
import { getAssociatedTokenAddress } from "../utils/tokenUtils";
import { DEVNET_RPC } from "../config/constants";
import { PublicKey as PK } from "@solana/web3.js";

const TOKEN_PROGRAM_ID = new PK("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA");

export interface IssueAttendanceBadgeParams {
  eventPda: string;
  attendee: string;
  metadataUri: string;
}

export async function apiIssueAttendanceBadge(
  params: IssueAttendanceBadgeParams
): Promise<{ signature: string; badgeMint: string }> {
  const connection = new Connection(DEVNET_RPC, "confirmed");
  const provider = createProvider(phantomWalletAdapter, connection);
  const program = getProgram(provider);
  const wallet = phantomWalletAdapter.getPublicKey();
  if (!wallet) throw new Error("Wallet not connected");

  const eventPubkey = new PublicKey(params.eventPda);
  const attendeePubkey = new PublicKey(params.attendee);

  // Derive PDAs
  const [userAttendancePda] = findUserAttendancePda(attendeePubkey);
  const [badgeCollectionPda] = findBadgeCollectionPda();

  // Fetch user attendance to determine tier
  const attendance = await program.account.userAttendanceRecord.fetchNullable(userAttendancePda);
  if (!attendance) {
    throw new Error("User attendance record not found. Check-in first.");
  }

  // Badge mint will be generated by the program
  const badgeMint = PublicKey.default; // Placeholder - program creates this

  const attendeeTokenAccount = getAssociatedTokenAddress(badgeMint, attendeePubkey);

  const tx = await program.methods
    .issueAttendanceBadge(params.metadataUri)
    .accounts({
      user: wallet,
      attendee: attendeePubkey,
      event: eventPubkey,
      userAttendanceRecord: userAttendancePda,
      badgeCollection: badgeCollectionPda,
      badgeMint,
      attendeeTokenAccount,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .rpc();

  return {
    signature: tx,
    badgeMint: badgeMint.toBase58(),
  };
}
